package com.cm.media.entity.search

data class SearchResult(
    val id: Int,
    val createdTime: Long,
    val lastModifiedTime: Long,
    val isDelete: Int,
    val version: Int,
    val type: Int,
    val source: Int,
    var name: String,
    var info: String,
    var img: String,
    var area: String,
    var year: String,
    var sourceScore: String,
    val sourceIsVip: Int,
    val sourcePlaySum: Int,
    var sourcePlaySumText: String,
    val isVip: Int,
    var updateText: String,
    val playSum: Int,
    val isTrailer: Int,
    val sourceOrderHot: Int,
    val sourceUrl: String,
    val isHas: Int,
    val season: String,
    val isOver: Int,
    var esKws: String,
    var esTags: String,
    var bannerText: String,
    var bannerDate: String,
    val plays: List<PlayUrl>,
    val detail: SearchDetail,
    val sourceSort: Int
)