package com.cm.media.entity.vod

data class Vod(
    val id: Int,
    val createdTime: Long,
    val lastModifiedTime: Long,
    val isDelete: Int,
    val version: Int,
    val type: Int,
    val source: Int,
    val name: String,
    val info: String,
    val img: String,
    val area: String,
    val year: String,
    val sourceScore: String,
    val SourceIsVip: Int,
    val sourcePlaySum: Int,
    val sourcePlaySumText: String,
    val isVip: Int,
    val updateText: String,
    val playSum: String,
    val isTrailer: Int,
    val sourceOrderHot: Long,
    val sourceUrl: String,
    val isHas: Int,
    val season: String,
    val isOver: String,
    val esKws: String,
    val esTags: String,
    val bannerText: String,
    val bannerData: String,
    val sourceSort: Int
)